import { Role, Team, User, AuditLog, NotificationItem } from './types';

export const INITIAL_ROLES: Role[] = [
  {
    id: 'r-ceo',
    code: 'CEO',
    name: 'CEO',
    description: 'Executive visibility across the company. Reviews critical strategic issues and escalation decisions. Does not perform operational actions.',
    permissions: ['view:dashboard:ceo', 'view:financials', 'view:all_projects', 'view:audit_logs', 'view:pipeline', 'decide:ceo_escalation']
  },
  {
    id: 'r-cto',
    code: 'CTO',
    name: 'CTO',
    description: 'Technology leadership across engineering delivery, platform architecture, and execution quality.',
    permissions: ['view:all_projects', 'view:engineering_workload', 'view:technical_progress', 'view:reports', 'manage:engineering', 'create:lead', 'edit:lead']
  },
  {
    id: 'r-bh',
    code: 'BUSINESS_HEAD',
    name: 'Business Head',
    description: 'Leads commercial and business development activities, pre-sales pipeline, and customer opportunities.',
    permissions: ['create:lead', 'view:sales_pipeline', 'view:commercials', 'view:assigned_projects', 'view:reports']
  },
  {
    id: 'r-ed',
    code: 'ENG_DIRECTOR',
    name: 'Engineering Director',
    description: 'Oversees engineering execution, technical feasibility, project workload, and solution budgets.',
    permissions: ['create:lead', 'view:engineering_workload', 'view:technical_progress', 'view:solution_budget', 'view:reports']
  },
  {
    id: 'r-pm',
    code: 'PROJECT_MANAGER',
    name: 'Project Manager',
    description: 'Central operational controller. Manages Gantt, task assignments, milestones, procurement coordination, and timeline delivery.',
    permissions: ['manage:projects', 'assign:tasks', 'manage:milestones', 'view:all_teams', 'review:leads', 'coordinate:procurement', 'create:lead', 'edit:lead']
  },
  {
    id: 'r-pe',
    code: 'PROJECT_ENGINEER',
    name: 'Project Engineer',
    description: 'Future operational support role. Supports PM in managing assigned project execution and sub-tasks.',
    permissions: ['manage:assigned_tasks', 'view:assigned_projects', 'review:daily_updates', 'escalate:blocker', 'create:lead', 'edit:lead']
  },
  {
    id: 'r-tl',
    code: 'TEAM_LEAD',
    name: 'Team Lead',
    description: 'Manages team capacity, reviews PM assignments, suggests task rescheduling or reassignments, and monitors daily updates.',
    permissions: ['view:team_workload', 'suggest:task_change', 'review:team_updates', 'escalate:resource_conflict', 'create:lead', 'edit:lead']
  },
  {
    id: 'r-emp',
    code: 'EMPLOYEE',
    name: 'Team Member',
    description: 'Executes assigned tasks across multiple projects, submits daily work logs, and reports blockers.',
    permissions: ['view:assigned_tasks', 'update:task_status', 'submit:daily_update', 'report:blocker', 'create:lead', 'edit:lead']
  },
  {
    id: 'r-sales',
    code: 'SALES',
    name: 'Sales Executive',
    description: 'Generates and updates customer leads, manages customer documentation, and tracks proposal negotiations.',
    permissions: ['create:lead', 'edit:own_leads', 'upload:customer_docs', 'view:lead_status']
  },
  {
    id: 'r-proc',
    code: 'PROCUREMENT',
    name: 'Procurement / Costing',
    description: 'Handles RFQs, vendor quotations, material pricing, purchase orders, and procurement tracking.',
    permissions: ['view:costing_requests', 'update:vendor_prices', 'manage:rfq', 'update:material_status']
  },
  {
    id: 'r-exec',
    code: 'EXECUTION',
    name: 'Execution',
    description: 'Site Assembly, Wiring, Panel Fabrication, Mechanical Integration & Commissioning.',
    permissions: ['view:execution_tasks', 'update:site_progress', 'report:site_blocker']
  },
  {
    id: 'r-admin',
    code: 'SYSTEM_ADMIN',
    name: 'System Administrator',
    description: 'Technical platform administrator. Manages user provisioning, master data, roles, and system settings.',
    permissions: ['manage:users', 'manage:teams', 'manage:roles', 'view:audit_logs', 'manage:settings']
  }
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 't-sw',
    code: 'SOFTWARE',
    name: 'Software Team',
    description: 'PLC, SCADA, HMI, C#/.NET Automation Software, and Cloud/Edge Integration.',
    team_lead_id: 'u-tl-sw',
    team_lead_name: 'Arun Kumar',
    member_count: 0,
    status: 'ACTIVE',
    created_at: '2026-01-10T09:00:00Z'
  },
  {
    id: 't-vision',
    code: 'VISION',
    name: 'Vision Team',
    description: '2D/3D Industrial Vision, OpenCV, Cognex/Keyence, AI Deep Learning Inspection.',
    team_lead_id: 'u-tl-vis',
    team_lead_name: 'Vanippriya',
    member_count: 0,
    status: 'ACTIVE',
    created_at: '2026-01-10T09:00:00Z'
  },
  {
    id: 't-robotics',
    code: 'ROBOTICS',
    name: 'Robotics & Solutions Team',
    description: 'FANUC, KUKA, ABB Robot Simulation, EOAT Design, Motion Control & AMR/AGV.',
    team_lead_id: 'u-tl-rob',
    team_lead_name: 'Aakash',
    member_count: 0,
    status: 'ACTIVE',
    created_at: '2026-01-10T09:00:00Z'
  },
  {
    id: 't-procurement',
    code: 'PROCUREMENT',
    name: 'Procurement / Costing Team',
    description: 'BOM Cost Estimation, Vendor Management, RFQ Processing & Logistics.',
    team_lead_name: 'Not Assigned',
    member_count: 0,
    status: 'ACTIVE',
    created_at: '2026-01-10T09:00:00Z'
  },
  {
    id: 't-execution',
    code: 'EXECUTION',
    name: 'Execution Team',
    description: 'Site Assembly, Wiring, Panel Fabrication, Mechanical Integration & Commissioning.',
    team_lead_name: 'Not Assigned',
    member_count: 0,
    status: 'ACTIVE',
    created_at: '2026-01-10T09:00:00Z'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u-ceo',
    employee_id: 'CYA-001',
    name: 'Bernard Hamilton',
    email: 'bernard.hamilton@careyu.com',
    phone: '+91 98765 00001',
    role_id: 'r-ceo',
    role_code: 'CEO',
    role_name: 'CEO',
    status: 'ACTIVE',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'u-cto',
    employee_id: 'CYA-001A',
    name: 'IlayaRaja',
    email: 'priya.menon@careyu.com',
    phone: '+91 98765 00015',
    role_id: 'r-cto',
    role_code: 'CTO',
    role_name: 'CTO',
    reporting_manager_id: 'u-ceo',
    status: 'ACTIVE',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z'
  },
  {
    id: 'u-bh',
    employee_id: 'CYA-002',
    name: 'Sharadha Patil',
    email: 'shradha.patil@careyu.com',
    phone: '+91 98765 00002',
    role_id: 'r-bh',
    role_code: 'BUSINESS_HEAD',
    role_name: 'Business Head',
    reporting_manager_id: 'u-ceo',
    status: 'ACTIVE',
    created_at: '2026-01-02T00:00:00Z',
    updated_at: '2026-01-02T00:00:00Z'
  },
  {
    id: 'u-ed',
    employee_id: 'CYA-003',
    name: 'Sabarigiri',
    email: 'sabarigiri.t@careyu.com',
    phone: '+91 98765 00003',
    role_id: 'r-ed',
    role_code: 'ENG_DIRECTOR',
    role_name: 'Engineering Director',
    reporting_manager_id: 'u-ceo',
    status: 'ACTIVE',
    created_at: '2026-01-02T00:00:00Z',
    updated_at: '2026-01-02T00:00:00Z'
  },
  {
    id: 'u-pm',
    employee_id: 'CYA-004',
    name: 'Arivan',
    email: 'arivan@careyu.com',
    phone: '+91 98765 00004',
    role_id: 'r-pm',
    role_code: 'PROJECT_MANAGER',
    role_name: 'Project Manager',
    reporting_manager_id: 'u-ceo',
    status: 'ACTIVE',
    created_at: '2026-01-03T00:00:00Z',
    updated_at: '2026-01-03T00:00:00Z'
  },
  {
    id: 'u-tl-sw',
    employee_id: 'CYA-010',
    name: 'Arun Kumar',
    email: 'arun@careyu.com',
    phone: '+91 98765 00010',
    role_id: 'r-tl',
    role_code: 'TEAM_LEAD',
    role_name: 'Team Lead',
    team_id: 't-sw',
    team_name: 'Software Team',
    reporting_manager_id: 'u-pm',
    status: 'ACTIVE',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z'
  },
  {
    id: 'u-tl-vis',
    employee_id: 'CYA-011',
    name: 'Vanippriya',
    email: 'vani@careyu.com',
    phone: '+91 98765 00011',
    role_id: 'r-tl',
    role_code: 'TEAM_LEAD',
    role_name: 'Team Lead',
    team_id: 't-vision',
    team_name: 'Vision Team',
    reporting_manager_id: 'u-pm',
    status: 'ACTIVE',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z'
  },
  {
    id: 'u-tl-rob',
    employee_id: 'CYA-012',
    name: 'Aakash',
    email: 'robotlead1@careyu.ai',
    phone: '+91 98765 00012',
    role_id: 'r-tl',
    role_code: 'TEAM_LEAD',
    role_name: 'Team Lead',
    team_id: 't-robotics',
    team_name: 'Robotics & Solutions Team',
    reporting_manager_id: 'u-pm',
    status: 'ACTIVE',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z'
  },
  {
    id: 'u-emp-kabitha',
    employee_id: 'CYA-020',
    name: 'Kabitha',
    email: 'kabitha@careyu.ai',
    phone: '',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-sw',
    team_name: 'Software Team',
    team_lead_id: 'u-tl-sw',
    team_lead_name: 'Arun Kumar',
    reporting_manager_id: 'u-tl-sw',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-sw',
    employee_id: 'CYA-020',
    name: 'Karthik',
    email: 'karthik@careyu.com',
    phone: '+91 98765 00020',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-sw',
    team_name: 'Software Team',
    team_lead_id: 'u-tl-sw',
    team_lead_name: 'Arun',
    reporting_manager_id: 'u-tl-sw',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-sw-2',
    employee_id: 'CYA-021',
    name: 'Deepak',
    email: 'deepak@careyu.com',
    phone: '+91 98765 00021',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-sw',
    team_name: 'Software Team',
    team_lead_id: 'u-tl-sw',
    team_lead_name: 'Arun',
    reporting_manager_id: 'u-tl-sw',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-sw-3',
    employee_id: 'CYA-022',
    name: 'Meena',
    email: 'meena@careyu.com',
    phone: '+91 98765 00022',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-sw',
    team_name: 'Software Team',
    team_lead_id: 'u-tl-sw',
    team_lead_name: 'Arun',
    reporting_manager_id: 'u-tl-sw',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-vis-1',
    employee_id: 'CYA-023',
    name: 'Sanjay',
    email: 'sanjay@careyu.com',
    phone: '+91 98765 00023',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-vision',
    team_name: 'Vision Team',
    team_lead_id: 'u-tl-vis',
    team_lead_name: 'Vani',
    reporting_manager_id: 'u-tl-vis',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-vis-2',
    employee_id: 'CYA-024',
    name: 'Lakshmi',
    email: 'lakshmi@careyu.com',
    phone: '+91 98765 00024',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-vision',
    team_name: 'Vision Team',
    team_lead_id: 'u-tl-vis',
    team_lead_name: 'Vani',
    reporting_manager_id: 'u-tl-vis',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-rob-1',
    employee_id: 'CYA-025',
    name: 'Rahul',
    email: 'rahul@careyu.com',
    phone: '+91 98765 00025',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-robotics',
    team_name: 'Robotics & Solutions Team',
    team_lead_id: 'u-tl-rob',
    team_lead_name: 'Aakash',
    reporting_manager_id: 'u-tl-rob',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-rob-2',
    employee_id: 'CYA-026',
    name: 'Divya',
    email: 'divya@careyu.com',
    phone: '+91 98765 00026',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-robotics',
    team_name: 'Robotics & Solutions Team',
    team_lead_id: 'u-tl-rob',
    team_lead_name: 'Aakash',
    reporting_manager_id: 'u-tl-rob',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-rob-3',
    employee_id: 'CYA-027',
    name: 'Vikram',
    email: 'vikram@careyu.com',
    phone: '+91 98765 00027',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-robotics',
    team_name: 'Robotics & Solutions Team',
    team_lead_id: 'u-tl-rob',
    team_lead_name: 'Aakash',
    reporting_manager_id: 'u-tl-rob',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-rob-4',
    employee_id: 'CYA-028',
    name: 'Nisha',
    email: 'nisha@careyu.com',
    phone: '+91 98765 00028',
    role_id: 'r-emp',
    role_code: 'EMPLOYEE',
    role_name: 'Team Member',
    team_id: 't-robotics',
    team_name: 'Robotics & Solutions Team',
    team_lead_id: 'u-tl-rob',
    team_lead_name: 'Aakash',
    reporting_manager_id: 'u-tl-rob',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-tl-proc',
    employee_id: 'CYA-013',
    name: 'Suresh',
    email: 'suresh@careyu.com',
    phone: '+91 98765 00013',
    role_id: 'r-tl',
    role_code: 'TEAM_LEAD',
    role_name: 'Team Lead',
    team_id: 't-procurement',
    team_name: 'Procurement / Costing Team',
    reporting_manager_id: 'u-pm',
    status: 'ACTIVE',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z'
  },
  {
    id: 'u-emp-proc-1',
    employee_id: 'CYA-029',
    name: 'Anitha',
    email: 'anitha@careyu.com',
    phone: '+91 98765 00029',
    role_id: 'r-proc',
    role_code: 'PROCUREMENT',
    role_name: 'Procurement / Costing',
    team_id: 't-procurement',
    team_name: 'Procurement / Costing Team',
    team_lead_id: 'u-tl-proc',
    team_lead_name: 'Suresh',
    reporting_manager_id: 'u-tl-proc',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-proc-2',
    employee_id: 'CYA-030',
    name: 'Manoj',
    email: 'manoj@careyu.com',
    phone: '+91 98765 00030',
    role_id: 'r-proc',
    role_code: 'PROCUREMENT',
    role_name: 'Procurement / Costing',
    team_id: 't-procurement',
    team_name: 'Procurement / Costing Team',
    team_lead_id: 'u-tl-proc',
    team_lead_name: 'Suresh',
    reporting_manager_id: 'u-tl-proc',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-tl-exec',
    employee_id: 'CYA-014',
    name: 'Ramesh',
    email: 'ramesh@careyu.com',
    phone: '+91 98765 00014',
    role_id: 'r-tl',
    role_code: 'TEAM_LEAD',
    role_name: 'Team Lead',
    team_id: 't-execution',
    team_name: 'Execution Team',
    reporting_manager_id: 'u-pm',
    status: 'ACTIVE',
    created_at: '2026-01-05T00:00:00Z',
    updated_at: '2026-01-05T00:00:00Z'
  },
  {
    id: 'u-emp-exec-1',
    employee_id: 'CYA-031',
    name: 'Gopal',
    email: 'gopal@careyu.com',
    phone: '+91 98765 00031',
    role_id: 'r-exec',
    role_code: 'EXECUTION',
    role_name: 'Execution',
    team_id: 't-execution',
    team_name: 'Execution Team',
    team_lead_id: 'u-tl-exec',
    team_lead_name: 'Ramesh',
    reporting_manager_id: 'u-tl-exec',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-exec-2',
    employee_id: 'CYA-032',
    name: 'Sita',
    email: 'sita@careyu.com',
    phone: '+91 98765 00032',
    role_id: 'r-exec',
    role_code: 'EXECUTION',
    role_name: 'Execution',
    team_id: 't-execution',
    team_name: 'Execution Team',
    team_lead_id: 'u-tl-exec',
    team_lead_name: 'Ramesh',
    reporting_manager_id: 'u-tl-exec',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-exec-3',
    employee_id: 'CYA-033',
    name: 'Farhan',
    email: 'farhan@careyu.com',
    phone: '+91 98765 00033',
    role_id: 'r-exec',
    role_code: 'EXECUTION',
    role_name: 'Execution',
    team_id: 't-execution',
    team_name: 'Execution Team',
    team_lead_id: 'u-tl-exec',
    team_lead_name: 'Ramesh',
    reporting_manager_id: 'u-tl-exec',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-exec-4',
    employee_id: 'CYA-034',
    name: 'Kavya',
    email: 'kavya@careyu.com',
    phone: '+91 98765 00034',
    role_id: 'r-exec',
    role_code: 'EXECUTION',
    role_name: 'Execution',
    team_id: 't-execution',
    team_name: 'Execution Team',
    team_lead_id: 'u-tl-exec',
    team_lead_name: 'Ramesh',
    reporting_manager_id: 'u-tl-exec',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-emp-exec-5',
    employee_id: 'CYA-035',
    name: 'Imran',
    email: 'imran@careyu.com',
    phone: '+91 98765 00035',
    role_id: 'r-exec',
    role_code: 'EXECUTION',
    role_name: 'Execution',
    team_id: 't-execution',
    team_name: 'Execution Team',
    team_lead_id: 'u-tl-exec',
    team_lead_name: 'Ramesh',
    reporting_manager_id: 'u-tl-exec',
    status: 'ACTIVE',
    created_at: '2026-01-08T00:00:00Z',
    updated_at: '2026-01-08T00:00:00Z'
  },
  {
    id: 'u-admin',
    employee_id: 'CYA-SYS-001',
    name: 'System Administrator',
    email: 'admin@careyu.com',
    phone: '+91 98765 99999',
    role_id: 'r-admin',
    role_code: 'SYSTEM_ADMIN',
    role_name: 'System Administrator',
    status: 'ACTIVE',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z'
  }
];

export const INITIAL_AUDITS: AuditLog[] = [];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
